# This workflow generates a debug APK for the android project.

#Name of the workflow
name: Generate Debug APK

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_android_project:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup up JDK environment
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          
      # Build android project with Gradle
      - name: Build project with Gradle
        run: ./gradlew build
        
      # Build debug apk
      - name: Build Release APK
        run: |
          ./gradlew clean assembleDebug

      # Example use of `signedReleaseFile` output -- not needed
      - uses: actions/upload-artifact@v3
        with:
          name: Signed app bundle
          path: app/build/outputs/apk/debug/app-debug.apk
